# Generated by Django 5.2.11 on 2026-02-21 11:57

import Shorten.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shorten", "0002_shortenedurl_ip_address_alter_shortenedurl_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortenedurl",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="short_code",
            field=models.CharField(
                db_index=True,
                default=Shorten.models.generate_short_code,
                max_length=20,
                unique=True,
            ),
        ),
    ]
